//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTPlayer.Localizations {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BTPlayer.Localizations.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   About に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AboutMenuCaption {
            get {
                return ResourceManager.GetString("AboutMenuCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add Device に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AddDeviceMenuCaption {
            get {
                return ResourceManager.GetString("AddDeviceMenuCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unable to create an AudioPlaybackConnection. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AudioPlaybackConnectionError {
            get {
                return ResourceManager.GetString("AudioPlaybackConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You cannot delete a device that is currently connected. Please disconnect it first. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BluetoothAlreadyDeviceDelete {
            get {
                return ResourceManager.GetString("BluetoothAlreadyDeviceDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please select the device you want to delete. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BluetoothDeleteDevice {
            get {
                return ResourceManager.GetString("BluetoothDeleteDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to delete {0}? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BluetoothDeviceDeleteConfirm {
            get {
                return ResourceManager.GetString("BluetoothDeviceDeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to delete the device.
        ///{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BluetoothDeviceDeleteFailed {
            get {
                return ResourceManager.GetString("BluetoothDeviceDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to delete the device.
        ///Status: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BluetoothDeviceDeleteFailedS {
            get {
                return ResourceManager.GetString("BluetoothDeviceDeleteFailedS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to verify Bluetooth functionality. 
        ///{0}
        ///The application will now close. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BluetoothException {
            get {
                return ResourceManager.GetString("BluetoothException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The process was aborted. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CancelledCaption {
            get {
                return ResourceManager.GetString("CancelledCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connect に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConnectCaption {
            get {
                return ResourceManager.GetString("ConnectCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connected: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConnectedNameCaption {
            get {
                return ResourceManager.GetString("ConnectedNameCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connected に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConnectionConnectCaption {
            get {
                return ResourceManager.GetString("ConnectionConnectCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Disconnected に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConnectionDisconectCaption {
            get {
                return ResourceManager.GetString("ConnectionDisconectCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   failed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConnectionFailedCaption {
            get {
                return ResourceManager.GetString("ConnectionFailedCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ready に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConnectionReadyCaption {
            get {
                return ResourceManager.GetString("ConnectionReadyCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unknown に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConnectionUnknownCaption {
            get {
                return ResourceManager.GetString("ConnectionUnknownCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Current version: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CurrentCaption {
            get {
                return ResourceManager.GetString("CurrentCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Detected に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DetectedCaption {
            get {
                return ResourceManager.GetString("DetectedCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Another device is already connected. Please disconnect it first. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DeviceAlreadyConnectCaption {
            get {
                return ResourceManager.GetString("DeviceAlreadyConnectCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Device List に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DeviceListCaption {
            get {
                return ResourceManager.GetString("DeviceListCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Device name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DeviceName {
            get {
                return ResourceManager.GetString("DeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The application cannot be started because the device is not connected. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DeviceNotConnectedCaption {
            get {
                return ResourceManager.GetString("DeviceNotConnectedCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please select a device. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DeviceSelectionCaption {
            get {
                return ResourceManager.GetString("DeviceSelectionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Disconnect に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DisconnectCaption {
            get {
                return ResourceManager.GetString("DisconnectCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Disconnect failed.
        ///{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DisconnectError {
            get {
                return ResourceManager.GetString("DisconnectError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Done に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DoneCaption {
            get {
                return ResourceManager.GetString("DoneCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Download is currently in progress. If you stop the download, the downloaded data will be lost.
        ///Are you sure you want to continue? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DownloadAbortConfirmCaption {
            get {
                return ResourceManager.GetString("DownloadAbortConfirmCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} KiB out of {1} KiB downloaded. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DownloadingCaption {
            get {
                return ResourceManager.GetString("DownloadingCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorCaption {
            get {
                return ResourceManager.GetString("ErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An error has occurred. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorOccuredText {
            get {
                return ResourceManager.GetString("ErrorOccuredText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExitCaption {
            get {
                return ResourceManager.GetString("ExitCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please run Connect first. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FirstConnectCaption {
            get {
                return ResourceManager.GetString("FirstConnectCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Downloading... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormDownloadingCaption {
            get {
                return ResourceManager.GetString("FormDownloadingCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Information に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InformationCaption {
            get {
                return ResourceManager.GetString("InformationCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Initializing... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InitializingText {
            get {
                return ResourceManager.GetString("InitializingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Latest version: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LatestCaption {
            get {
                return ResourceManager.GetString("LatestCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Log に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LogCaption {
            get {
                return ResourceManager.GetString("LogCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Aborted に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSGBoxAbortedCaption {
            get {
                return ResourceManager.GetString("MSGBoxAbortedCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Confirm に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSGBoxConfirmCaption {
            get {
                return ResourceManager.GetString("MSGBoxConfirmCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is no Internet connection. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NetworkNotConnectedCaption {
            get {
                return ResourceManager.GetString("NetworkNotConnectedCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (No Name) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NoNameCaption {
            get {
                return ResourceManager.GetString("NoNameCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No Bluetooth functionality was found on this PC.
        ///The application will now close. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotBluetooth {
            get {
                return ResourceManager.GetString("NotBluetooth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I couldn&apos;t open the Bluetooth settings screen.
        ///{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotOpenBluetoothSettings {
            get {
                return ResourceManager.GetString("NotOpenBluetoothSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OpenAsync failed.
        ///{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OpenAsyncError {
            get {
                return ResourceManager.GetString("OpenAsyncError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OpenCaption {
            get {
                return ResourceManager.GetString("OpenCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open failed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OpenFailedCaption {
            get {
                return ResourceManager.GetString("OpenFailedCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Processing... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ProcessingText {
            get {
                return ResourceManager.GetString("ProcessingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Processing type unknown. Closes dialog after a few seconds. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ProcessUnknownText {
            get {
                return ResourceManager.GetString("ProcessUnknownText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} / {1} Files completed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ProgressText {
            get {
                return ResourceManager.GetString("ProgressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Refresh List に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RefreshDeviceCaption {
            get {
                return ResourceManager.GetString("RefreshDeviceCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove Device に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RemoveDiviceMenuCaption {
            get {
                return ResourceManager.GetString("RemoveDiviceMenuCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Selected: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SelectedNameCaption {
            get {
                return ResourceManager.GetString("SelectedNameCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShowCaption {
            get {
                return ResourceManager.GetString("ShowCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You can update your application.
        ///
        ///Do you want to open the GitHub site? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SiteOpenCaption {
            get {
                return ResourceManager.GetString("SiteOpenCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   StartAsync failed.
        ///{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StartAsyncError {
            get {
                return ResourceManager.GetString("StartAsyncError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   State に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StateCaption {
            get {
                return ResourceManager.GetString("StateCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Status: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StatusCaption {
            get {
                return ResourceManager.GetString("StatusCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   It is now running in the system tray. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TasktrayMinimized {
            get {
                return ResourceManager.GetString("TasktrayMinimized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The app is now running in the system tray.
        ///Connected: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TasktrayMinimizedwConnected {
            get {
                return ResourceManager.GetString("TasktrayMinimizedwConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An error has occured.
        ///{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnExpectedErrorCaption {
            get {
                return ResourceManager.GetString("UnExpectedErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update completed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UpdateCompletedCaption {
            get {
                return ResourceManager.GetString("UpdateCompletedCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Application updates are available.
        ///Do you want to update? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UpdateConfirmCaption {
            get {
                return ResourceManager.GetString("UpdateConfirmCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UpdateMenuCaption {
            get {
                return ResourceManager.GetString("UpdateMenuCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You are using the latest version of the application. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UptodateCaption {
            get {
                return ResourceManager.GetString("UptodateCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Warning に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WarningCaption {
            get {
                return ResourceManager.GetString("WarningCaption", resourceCulture);
            }
        }
    }
}
